### ISSUE TITLE
Jank when sync/indexing in progress

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#1086]
Version: v0.0.16(2)

We seem to get a lot of jank when loading and sync are in progress, especially on the profile tab.

- Background gradients sometimes render at different times to the rest of the UI
- Tab switching seems janky sometimes
- Following/unfollowing has long delays before surfacing confirmation toast.

We should be doing all work off main thread, so this is a bit surprising. This seems most pronounced on the profile tab, so there may be something going on with that one specifically.

**Comment by bfollington** [comment]
Tab switching lag & general performance on the profile was due to a missing LazyVStack in the note list: https://github.com/subconsciousnetwork/subconscious/pull/1096

> Following/unfollowing has long delays before surfacing confirmation toast.

I have a hunch that https://github.com/subconsciousnetwork/subconscious/issues/658 will fix this.

**Comment by bfollington** [comment]
I believe we've resolved all three of the original issues now.

> Background gradients sometimes render at different times to the rest of the UI

Fixed in https://github.com/subconsciousnetwork/subconscious/pull/1081

> Tab switching seems janky sometimes

Fixed in https://github.com/subconsciousnetwork/subconscious/pull/1096

> Following/unfollowing has long delays before surfacing confirmation toast.

_partially_ fixed by https://github.com/subconsciousnetwork/subconscious/pull/1096, needs more testing to confirm if there is an additional latency.
