### ISSUE TITLE
Multiplayer backlinks

### ISSUE THREAD

**Issue by gordonbrander** [subconsciousnetwork/subconscious#323]
## Story

As a user, when I am visiting a note, I want to see related notes from spheres I follow, so that I have ambient awareness of related thoughts my follows have had on this topic.

**Comment by gretchenfrage** [comment]
I'm curious if you have thoughts or plans on how to implement this--it's a concept I find particularly vexing.

The way I see it, the fundamental issue here is how to define whether a particular backlink is "relevant." This is, in such a situation:

- user A makes a post
- user B makes a post that backlinks to A's post
- user C (who may be A or B or someone else) views A's post

Should C see B's backlinked post? More generally, if there are say thousands of posts in existence which backlink to A's post, how should they be ranked, and which ones should be cut off in the UI? Especially if bots go out there and start generating everything from potentially-relevant associated information to pure spam.

Probably approaches can be divided into two categories: ones which rely on some objective ranking, and ones which allow for different lenses of viewing to maintain different rankings.

Objective ranking
---

An objective ranking would entail all nodes reaching consensus on the relevancy (ranking or boolean) of a particular backlink from the perspective of the original post.

Pros:
- compatible with DHTs. if each node can verify that a particular backlink is "objectively relevant" as defined by the protocol, they can come together to encode a {post id -> [post ids with relevant backlinks]} mapping in some DHT, which achieves efficient robustness.

Cons:
- relying on objective consensus of what is relevant to what is of course viscerally concerning, seeing-like-a-state vibes stuff. I think that knowledge systems work a lot better where people are able to fluidly and continuously dissent to partial degrees, rather than being forced into a binary between total consensus and hard forking.

Possible consensus algorithms:
- **"original poster soverignity"**: Let the author of a post arbitrarily decide the set and sequence of relevant replies, and sign it similarly to existing NNS tech.
  
  Pros:
  - a form of moderation
  - would be relatively easy to incorporate into NNS

  Cons:
  - censorious, opposition becomes difficult to discover
  - online-dependent: may rely on original poster having some online system to be notified of new responses in a activitypub-type way to sign new replies, without which new replies stop being discovered. on the other hand, it could be made such that the original poster can sign off on some generally interpretable rule for endorsing replies, such as "rank by degrees of separation of following from me to replier", that a replier could then use to construct a proof of endorsement without the original poster needing to be online.
- **"everything is relevant"**: Just consider everything relevant, nodes incorporate into the DHT anything anyone posts.

  Pros:
  - simple
  - non-censorious

  Cons: clear tragedy of the commons type problem
- **some sort of blockchain thing**: Sort of putting this in here for completeness. Use some sort of filecoin-type system to make the ability to post a backlink into the DHT scarce. Nodes in the DHT look at the blockchain to verify that the backlink should be incorporated into the DHT. I don't like this one.

  Pros: it partially avoids the problems of the other things

  Cons: it becomes pay-to-post and pay-to-spam.
- **some sort of a priori zero-knowledge proofs**: Figure out some way to have a computer look at a response and simply directly determine based on its content whether it's relevant objectively. I think this is isomorphic to solving philosophy.

  Pros: it's perfect

  Cons: it's impossible

Subjective ranking
---

A subjective ranking would entail allowing for different lenses of browsing (users, browsers, states or components within browsers) to maintain different perspectives regarding which backlinks and relevant and in what ranking to a particular original post.

Some example definitions for these perspectives could be:
- degrees of separation of following from the viewer to the replier
- minimum between degrees of separation of following from the viewer to the replier and the original poster to the replier, excepting links through users the viewer has blocked
- specifically replies that the original poster has negatively endorsed
- Etc...

The pro of subjective ranking is epistemic flexibility and whatnot, equal and opposite to the cons of objective ranking.

The con of subjective ranking is that disagreement on the data is fundamentally in tension with peer-to-peer data structures like DHTs. If one is to allow for nodes to disagree on the correct {post id -> [post ids with relevant backlinks]} mapping, they can't exactly deduplicate ranges of that mapping in a conventional DHT for efficiency and robustness and stuff.

The polar opposite way to implement such a thing would be for each node to just maintain a local index of all, or at least as many as it practically can, of the posts it could potentially find relevant as backlinks. So, for example, if a node wants to rank backlinks by degrees of separation of following, it can continuously fetch and index all the posts made by everyone they follow, and everyone one of those people follows, etc, and then consult this database. I think this is most similar to the activitypub style of approaching things.

The downsides of this are this are that it becomes heavy-weight and unscalable. If one is, say, using subconscious on their phone, they probably don't want their mobile app spending its various resources maintaining a constant firehose stream of the whole web. It would become straight-up not possible when the network scales to a certain rate of posting, which would drive users to begin to lose the informational capacity to see beyond their local social circle (unfortunate!). New users would have to wait for an extended period of time for the system to back-propagate, and that would be their first experience with the system.

Hybrid approach
---

One hybrid approach would be a federation-style approach. "A perspective is too expensive for each individual to have, so have people choose which perspective instance they want to connect to." The more straightforward way to do this would be by maintaining activitypub-style instance servers or server clusters. I worry about the centralizing tendencies to that--after all, email is a federated protocol, but it's become extremely centralized because of the high barriers to running your own email server reliably.

Alternatively, it's conceivable that if these perspectives could be expressed in some language capable of doing zero-knowledge proofs, then nodes of a particular perspective could form their own DHT with each other for it. This would be hard. It would also still be concerning in how it still leaves non-epistemic energy barriers against dissent.

I think the sort of north star platonic ideal of such peer-to-peer associative structures would be a system that uses DHT-reminiscent deduplication where overlaps in perspectives occur while still fluidly allowing partial disagreement. Unfortunately I am not aware of the existence of such a technology, and my attempts to research it have left me only with fear at the looming suspicion that it has something to do with category theory.
